version: '3.9'

services:
  analytics-datastore-elastic-search-01:
    depends_on:
      - create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ulimits:
     memlock:
      soft: -1
      hard: -1
    deploy:
      resources:
        limits:
          memory: ${ES_MEMORY_LIMIT:-3G}
        reservations:
          memory: ${ES_MEMORY_RESERVE:-500M}
      # placement:
      #   constraints:
      #     - "node.labels.name==node-1"
    environment:
      node.name: es01
      cluster.name: es-cluster
      discovery.seed_hosts: analytics-datastore-elastic-search-02,analytics-datastore-elastic-search-03
      cluster.initial_master_nodes: es01
      xpack.license.self_generated.type: basic
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'true'
      xpack.security.http.ssl.enabled: 'false'
      xpack.security.http.ssl.key: certs/es01/es01.key
      xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.http.ssl.certificate: certs/es01/es01.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate 
      xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.transport.ssl.certificate: certs/es01/es01.crt
      xpack.security.transport.ssl.key: certs/es01/es01.key
      ES_JAVA_OPTS: ${ES_HEAP_SIZE:--Xms2048m -Xmx2048m}
      search.max_buckets: 1000000
      search.default_search_timeout: -1
      ES_LOGSTASH_SYSTEM: ${ES_LOGSTASH_SYSTEM:-dev_password_only}
      ES_APM_SYSTEM: ${ES_APM_SYSTEM:-dev_password_only}
      ES_REMOTE_MONITORING_USER: ${ES_REMOTE_MONITORING_USER:-dev_password_only}
      ES_ELASTIC: ${ES_ELASTIC:-dev_password_only}
      ES_KIBANA_SYSTEM: ${ES_KIBANA_SYSTEM:-dev_password_only}
      ES_BEATS_SYSTEM: ${ES_BEATS_SYSTEM:-dev_password_only}
    volumes:
      - es01-data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs

  analytics-datastore-elastic-search-02:
    depends_on:
      - create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: ${ES_MEMORY_LIMIT:-3G}
        reservations:
          memory: ${ES_MEMORY_RESERVE:-500M}
      # placement:
      #   constraints:
      #     - "node.labels.name==node-2"
    environment:
      node.name: es02
      cluster.name: es-cluster
      discovery.seed_hosts: analytics-datastore-elastic-search-01,analytics-datastore-elastic-search-03
      cluster.initial_master_nodes: es01
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'true'
      xpack.license.self_generated.type: basic
      xpack.security.http.ssl.enabled: 'false'
      xpack.security.http.ssl.key: certs/es02/es02.key
      xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.http.ssl.certificate: certs/es02/es02.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate 
      xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.transport.ssl.certificate: certs/es02/es02.crt
      xpack.security.transport.ssl.key: certs/es02/es02.key
      ES_JAVA_OPTS: ${ES_HEAP_SIZE:--Xms2048m -Xmx2048m}
      search.max_buckets: 1000000
      search.default_search_timeout: -1
      ES_LOGSTASH_SYSTEM: ${ES_LOGSTASH_SYSTEM:-dev_password_only}
      ES_APM_SYSTEM: ${ES_APM_SYSTEM:-dev_password_only}
      ES_REMOTE_MONITORING_USER: ${ES_REMOTE_MONITORING_USER:-dev_password_only}
      ES_ELASTIC: ${ES_ELASTIC:-dev_password_only}
      ES_KIBANA_SYSTEM: ${ES_KIBANA_SYSTEM:-dev_password_only}
      ES_BEATS_SYSTEM: ${ES_BEATS_SYSTEM:-dev_password_only}
    volumes:
      - es02-data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs

  analytics-datastore-elastic-search-03:
    depends_on:
      - create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: ${ES_MEMORY_LIMIT:-3G}
        reservations:
          memory: ${ES_MEMORY_RESERVE:-500M}
      # placement:
      #   constraints:
      #     - "node.labels.name==node-3"
    environment:
      node.name: es03
      cluster.name: es-cluster
      discovery.seed_hosts: analytics-datastore-elastic-search-01,analytics-datastore-elastic-search-02
      cluster.initial_master_nodes: es01
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'true'
      xpack.license.self_generated.type: basic
      xpack.security.http.ssl.enabled: 'false'
      xpack.security.http.ssl.key: certs/es03/es03.key
      xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.http.ssl.certificate: certs/es03/es03.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate 
      xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.transport.ssl.certificate: certs/es03/es03.crt
      xpack.security.transport.ssl.key: certs/es03/es03.key
      ES_JAVA_OPTS: ${ES_HEAP_SIZE:--Xms2048m -Xmx2048m}
      search.max_buckets: 1000000
      search.default_search_timeout: -1
      ES_LOGSTASH_SYSTEM: ${ES_LOGSTASH_SYSTEM:-dev_password_only}
      ES_APM_SYSTEM: ${ES_APM_SYSTEM:-dev_password_only}
      ES_REMOTE_MONITORING_USER: ${ES_REMOTE_MONITORING_USER:-dev_password_only}
      ES_ELASTIC: ${ES_ELASTIC:-dev_password_only}
      ES_KIBANA_SYSTEM: ${ES_KIBANA_SYSTEM:-dev_password_only}
      ES_BEATS_SYSTEM: ${ES_BEATS_SYSTEM:-dev_password_only}
    volumes:
      - es03-data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs

volumes:
  es01-data:
  es02-data:
  es03-data:
  certs:
