projectName: platform
<<<<<<< HEAD
image: jembi/platform:openfn
=======
image: jembi/platform:2.3.2
>>>>>>> b31a3b1b41edfaad9b1c86dccd04ffc4cef43b45
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir
  - message-bus-kafka
  - analytics-datastore-elastic-search
  - dashboard-visualiser-kibana
  - data-mapper-logstash
  - dashboard-visualiser-jsreport
  - client-registry-santempi
  - message-bus-helper-hapi-proxy
  - job-scheduler-ofelia
  - kafka-mapper-consumer
  - kafka-unbundler-consumer
  - analytics-datastore-clickhouse
  - dashboard-visualiser-superset
  - monitoring
  - mpi-mediator
  - client-registry-jempi
  - identity-access-manager-keycloak
  - openhim-mapping-mediator
  - openfn
  - dashboard-visualiser-dhis2
