version: '3.9'

services:
  hapi-proxy:
    image: jembi/springproxyserver:20211217-170809.3f57ef5
    hostname: hapi-proxy
    environment:
      HAPI_SERVER_URL: ${HAPI_SERVER_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      HAPI_SERVER_VALIDATE_FORMAT: ${HAPI_SERVER_VALIDATE_FORMAT}
    deploy:
      replicas: ${HAPI_PROXY_INSTANCES}
      resources:
        limits:
          cpus: ${HAPI_PROXY_CPU_LIMIT}
          memory: ${HAPI_PROXY_MEMORY_LIMIT}
        reservations:
          cpus: ${HAPI_PROXY_CPU_RESERVE}
          memory: ${HAPI_PROXY_MEMORY_RESERVE}
