version: '3.9'

services:
  openhim-mapping-mediator:
    image: jembi/openhim-mediator-mapping:v3.0.0
    environment:
      OPENHIM_REGISTER: ${OPENHIM_REGISTER}
      MONGO_URL: ${OPENHIM_MONGO_URL}
      OPENHIM_URL: ${OPENHIM_URL}
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      brokers: "localhost:9092"
      clientId: "mapping-mediator"
      requestTimeout: 60000
      connectionTimeout: 60000
      groupId: "mapping-mediator"
    networks:
      openhim:
      mongo:

networks:
  openhim:
    name: openhim_public
    external: true
  mongo:
    name: openhim_mongo_public
    external: true
