version: '3.9'

services:
  prometheus_backup:
    image: prom/prometheus:v2.38.0
    user: root
    deploy:
      placement:
        constraints:
          - "node.labels.name!=node-1"
      replicas: 1
    volumes:
      - prometheus_data_backup:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - target: /etc/prometheus/prometheus.yml
        source: prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

configs:
  prometheus.yml:
    file: ./prometheus/prometheus.yml
    name: prometheus.yml-${prometheus_yml_DIGEST:?err}
    labels:
      name: prometheus

volumes:
  prometheus_data_backup:
