version: "3.9"

services:
  prometheus:
    deploy:
      placement:
        constraints:
          - "node.labels.name==${PROMETHEUS_PLACEMENT}"
      replicas: 1

  prometheus_backup:
    image: ${PROMETHEUS_BACKUP_IMAGE}
    user: root
    deploy:
      placement:
        constraints:
          - "node.labels.name!=${PROMETHEUS_BACKUP_PLACEMENT}"
      replicas: 1
    volumes:
      - prometheus_data_backup:/prometheus
      - ${DOCKER_SOCK_FOLDER}:/var/run/docker.sock:ro
    configs:
      - target: /etc/prometheus/prometheus.yml
        source: prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      public:
      default:


volumes:
  prometheus_data_backup:
