version: '3.3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    container_name: logstash
    labels:
      co.elastic.metrics/module: 'docker'
      co.elastic.metrics/metricsets: 'cpu,memory,diskio,info,healthcheck,container'
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/
      - logstash-config:/usr/share/logstash/config/

volumes:
  logstash-pipeline:
    external: true
  logstash-config:
    external: true
