version: '3.3'

services:
  mongo-1:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  mongo-2:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-2"

  mongo-3:
    deploy:
      placement:
        constraints:
          - "node.labels.name==secondary"
