version: '3.3'

services:
  openhim-core:
    deploy:
      replicas: 1

  openhim-console:
    deploy:
      replicas: 1

  hapi-fhir:
    deploy:
      replicas: 1

  hapi-db:
    deploy:
      replicas: 1

  hapi-proxy:
    deploy:
      replicas: 1
