name: Create go binaries for linux, windows and mac

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Releases
      run: ./get-cli.sh

    - name: Test binaries
      run: ./platform-linux help

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./platform-linux
          ./platform-macos
          ./platform.exe
          ./config.yml
          ./banner.txt
