version: '3.9'
services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: "lightning_dev"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
    image: "postgres:14.2-alpine"
    stop_grace_period: "3s"
    # volumes:
    #    - ./database_dump.sql:/docker-entrypoint-initdb.d/10-db_dump.sql

  web:
  
    image: openfn/lightning
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    # volumes:
    #   - "${LIGHTNING_VOLUME:-./priv/static:/app/priv/static}"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:4000/health_check}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    environment:
      - DISABLE_DB_SSL=true
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/lightning_dev
    ports:
      # - "${LIGHTNING_EXTERNAL_PORT:-127.0.0.1:${PORT}}:${URL_PORT}"
      - 4000:4000

volumes:
  postgres: {}
