version: '3.9'

services:
  openfn-postgres-1:
    environment:
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  openfn-postgres-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${OPENFN_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${OPENFN_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${OPENFN_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: openfn-postgres-2
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: openfn-postgres-2
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
    volumes:
      - 'openfn-postgres-2-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          cpus: ${OPENFN_POSTGRES_CPU_LIMIT}
          memory: ${OPENFN_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENFN_POSTGRES_CPU_RESERVE}
          memory: ${OPENFN_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      openfn-postgres:
      pg_backup_net:


  openfn-postgres-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${OPENFN_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${OPENFN_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${OPENFN_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: openfn-postgres-3
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-3
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
    volumes:
      - 'openfn-postgres-3-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          cpus: ${OPENFN_POSTGRES_CPU_LIMIT}
          memory: ${OPENFN_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENFN_POSTGRES_CPU_RESERVE}
          memory: ${OPENFN_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      openfn-postgres:
      pg_backup_net:


volumes:
  openfn-postgres-2-data:
  openfn-postgres-3-data:
