version: '3.9'

services:
  # container for executing config import scripts for creating the OpenHIM channels used by the Mediator
  kafka-mapper-consumer-config-importer:
    image: node:erbium-alpine
    networks:
      openhim:
      default:
    environment:
      OPENHIM_API_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_API_PASSWORD: ${OPENHIM_PASSWORD}
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      OPENHIM_CONSOLE_BASE_URL: ${OPENHIM_CONSOLE_BASE_URL}
    command: sh -c "node openhimConfig.js"
    configs:
      - source: kafka-mapper-consumer-openhimConfig.js
        target: /openhimConfig.js
      - source: kafka-mapper-consumer-consumer-ui-app.json
        target: /consumer-ui-app.json
    deploy:
      replicas: 1
      restart_policy:
        condition: none

configs:
  kafka-mapper-consumer-openhimConfig.js:
    file: ./openhimConfig.js
    name: kafka-mapper-consumer-openhimConfig.js-${fhir_ig_importer_config_importer_openhimConfig_js_DIGEST:?err}
    labels:
      name: kafka-mapper-consumer
  kafka-mapper-consumer-consumer-ui-app.json:
    file: ./consumer-ui-app.json
    name: kafka-mapper-consumer-consumer-ui-app.json-${kafka_mapper_consumer_ui_json_DIGEST:?err}
    labels:
      name: kafka-mapper-consumer

networks:
  openhim:
    name: openhim_public
    external: true
  default:
