version: '3.9'

services:
  postgres-1:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD:-instant101}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME:-admin}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE:-hapi}
      REPMGR_NODE_NETWORK_NAME: postgres-1
      REPMGR_PASSWORD: ${REPMGR_PASSWORD:-instant101}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-1
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1}
    volumes:
      - 'hapi-postgres-1-data:/bitnami/postgresql'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}

volumes:
  hapi-postgres-1-data:
