version: '3.9'

services:
  postgres-1:
    environment:
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  postgres-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD:-instant101}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME:-admin}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE:-hapi}
      REPMGR_NODE_NETWORK_NAME: postgres-2
      REPMGR_PASSWORD: ${REPMGR_PASSWORD:-instant101}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-2
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    volumes:
      - 'hapi-postgres-2-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}
    networks:
      default:
      pg_backup_net: {}


  postgres-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD:-instant101}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME:-admin}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE:-hapi}
      REPMGR_NODE_NETWORK_NAME: postgres-3
      REPMGR_PASSWORD: ${REPMGR_PASSWORD:-instant101}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-3
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    volumes:
      - 'hapi-postgres-3-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}
    networks:
      default:
      pg_backup_net: {}


volumes:
  hapi-postgres-2-data:
  hapi-postgres-3-data:
