version: '3.9'

services:
  hapi-fhir:
    image: hapiproject/hapi:v5.7.0
    environment:
      - spring.datasource.url=jdbc:postgresql://${POSTGRES_REPLICA_SET}/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.bulk_export_enabled=true
      - hapi.fhir.enable_repository_validating_interceptor=true
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - CATALINA_OPTS=-Xmx2g
    deploy:
      replicas: ${HAPI_FHIR_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${HAPI_FHIR_CPU_LIMIT}
          memory: ${HAPI_FHIR_MEMORY_LIMIT}
        reservations:
          cpus: ${HAPI_FHIR_CPU_RESERVE}
          memory: ${HAPI_FHIR_MEMORY_RESERVE}
