version: "3.9"

services:
  hapi-fhir:
    image: jembi/hapi:${HF_IMAGE_TAG}
    networks:
      mpi:
      public:
      default:
    environment:
      - HAPI_DB_SET=${HAPI_DB_SET}
      - HF_POSTGRESQL_USERNAME=${HF_POSTGRESQL_USERNAME}
      - HF_POSTGRESQL_PASSWORD=${HF_POSTGRESQL_PASSWORD}
      - HF_MAX_POOL_SIZE=${HF_MAX_POOL_SIZE}
      - FHIR_VERSION=${FHIR_VERSION}
      - JAVA_TOOL_OPTIONS=${HF_JAVA_OPTS}
      - CATALINA_OPTS=${HF_JAVA_OPTS}
    deploy:
      replicas: ${HAPI_FHIR_INSTANCES}
      placement:
        max_replicas_per_node: ${HAPI_FHIR_MAX_REPLICAS_PER_NODE}
      resources:
        limits:
          cpus: ${HAPI_FHIR_CPU_LIMIT}
          memory: ${HAPI_FHIR_MEMORY_LIMIT}
        reservations:
          cpus: ${HAPI_FHIR_CPU_RESERVE}
          memory: ${HAPI_FHIR_MEMORY_RESERVE}
    healthcheck:
      test: /bin/wget --no-verbose --tries=1 --spider http://localhost:8080/fhir/Organization?identifier=urn:healthcheck
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 2m

networks:
  mpi:
    name: mpi_public
    external: true
  public:
    name: hapi-fhir_public
    external: true
  default:
