version: "3.9"

services:
  # Proxies requests to internal services
  reverse-proxy-nginx:
    image: ${REVERSE_PROXY_NGINX_IMAGE}
    networks:
      public:
    deploy:
      replicas: ${REVERSE_PROXY_INSTANCES}
      placement:
        max_replicas_per_node: ${REVERSE_PROXY_NGINX_MAX_REPLICAS_PER_NODE}
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT}
          memory: ${NGINX_MEMORY_LIMIT}
        reservations:
          cpus: ${NGINX_CPU_RESERVE}
          memory: ${NGINX_MEMORY_RESERVE}

networks:
  public:
    name: reverse-proxy_public
    external: true
