version: '3.9'

services:
  # Proxies requests to internal services
  reverse-proxy-nginx:
    image: nginx:stable
    deploy:
      replicas: ${REVERSE_PROXY_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT:-0.8}
          memory: ${NGINX_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${NGINX_CPU_RESERVE:-0.05}
          memory: ${NGINX_MEMORY_RESERVE:-500M}

  # Runs certbot to renew TLS certificates
  ofelia:
    image: mcuadros/ofelia:v0.3.6
    deploy:
      replicas: 0
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - reverse-proxy-nginx
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.renew-certs.schedule: "@every 1440h" #60 days
      ofelia.job-run.renew-certs.image: "jembi/swarm-nginx-renewal:v1.0.0"
      ofelia.job-run.renew-certs.volume: '["renew-certbot-conf:/instant","/var/run/docker.sock:/var/run/docker.sock:ro"]'
      ofelia.job-run.renew-certs.environment: '["RENEWAL_EMAIL=${RENEWAL_EMAIL}", "STAGING=${STAGING}", "DOMAIN_NAME=${DOMAIN_NAME}", "SUBDOMAINS=${SUBDOMAINS}"]'
      ofelia.job-run.renew-certs.delete: "true"
