version: '3.9'

services:
  # Proxies requests to internal services
  reverse-proxy-nginx:
    image: nginx:stable
    deploy:
      replicas: ${REVERSE_PROXY_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT:-0}
          memory: ${NGINX_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${NGINX_CPU_RESERVE:-0.05}
          memory: ${NGINX_MEMORY_RESERVE:-500M}
