version: '3.9'

services:
  jempi-web:
    image: jembi/jempi-ui:${JEMPI_WEB_VERSION}
    environment:
      REACT_APP_JEMPI_BASE_API_HOST: ${REACT_APP_JEMPI_BASE_API_HOST}
      REACT_APP_JEMPI_BASE_API_PORT: ${REACT_APP_JEMPI_BASE_API_PORT}
      REACT_APP_ENABLE_SSO: ${KC_JEMPI_SSO_ENABLED}
      REACT_APP_MAX_UPLOAD_CSV_SIZE_IN_MEGABYTES: 128
      NODE_ENV: production
      KC_FRONTEND_URL: ${KC_FRONTEND_URL}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_JEMPI_CLIENT_ID: ${KC_JEMPI_CLIENT_ID}
      REACT_APP_SHOW_BRAND_LOGO: "false"
    deploy:
      replicas: ${JEMPI_WEB_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          memory: ${JEMPI_WEB_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_WEB_MEMORY_RESERVE}
    networks:
      reverse-proxy:
      keycloak:
      default:


networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  keycloak:
    name: keycloak_public
    external: true
  default:
