version: '3.9'

services:
  jempi-alpha-01:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-1
  
  jempi-alpha-02:
    image: ${JEMPI_ZERO_IMAGE}
    hostname: alpha-02
    volumes:
      - jempi-alpha-02-data:/dgraph
    deploy:
      placement:
        constraints:
          - node.labels.name == node-2
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_ALPHA_02_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_ALPHA_02_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-02:7081 --zero=jempi-zero-01:5080 --security whitelist=0.0.0.0/0 -o 1 --telemetry "sentry=false;"
    networks:
      jempi:

  jempi-alpha-03:
    image: ${JEMPI_ZERO_IMAGE}
    hostname: alpha-03
    volumes:
      - jempi-alpha-03-data:/dgraph
    deploy:
      placement:
          constraints:
            - node.labels.name == node-3
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_ALPHA_03_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_ALPHA_03_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-03:7082 --zero=jempi-zero-01:5080 --security whitelist=0.0.0.0/0 -o 2 --telemetry "sentry=false;"
    networks:
      jempi:

  jempi-ratel:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-1

volumes:
  jempi-alpha-02-data:
  jempi-alpha-03-data: 

networks:
  jempi:
    name: jempi_public
    external: true
