version: '3.9'

services:
  jempi-zero-01:
    image: dgraph/dgraph:v22.0.0
    volumes:
      - jempi-zero-01-data:/dgraph
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ZERO_01_MEMORY_LIMIT}
        reservations:
          memory: ${ZERO_01_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph zero --my=jempi-zero-01:5080 --replicas 1

  jempi-alpha-01:
    image: dgraph/dgraph:v22.0.0
    volumes:
      - jempi-alpha-01-data:/dgraph
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ALPHA_01_MEMORY_LIMIT}
        reservations:
          memory: ${ALPHA_01_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-01:7080 --zero=jempi-zero-01:5080 --security whitelist=0.0.0.0/0 --telemetry "sentry=false;"

  jempi-alpha-02:
    image: dgraph/dgraph:v22.0.0
    volumes:
      - jempi-alpha-02-data:/dgraph
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ALPHA_02_MEMORY_LIMIT}
        reservations:
          memory: ${ALPHA_02_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-02:7081 --zero=jempi-zero-01:5080 --security whitelist=0.0.0.0/0 -o 1 --telemetry "sentry=false;"

  jempi-alpha-03:
    image: dgraph/dgraph:v22.0.0
    volumes:
      - jempi-alpha-03-data:/dgraph
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ALPHA_03_MEMORY_LIMIT}
        reservations:
          memory: ${ALPHA_03_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-03:7082 --zero=jempi-zero-01:5080 --security whitelist=0.0.0.0/0 -o 2 --telemetry "sentry=false;"

  jempi-ratel:
    image: dgraph/ratel:v21.03.2
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${RATEL_MEMORY_LIMIT}
        reservations:
          memory: ${RATEL_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph-ratel

volumes:
  jempi-zero-01-data:
  jempi-alpha-01-data:
  jempi-alpha-02-data:
  jempi-alpha-03-data:
