version: "3.9"

services:
  jempi-alpha-01:
    image: ${JEMPI_ZERO_IMAGE}
    hostname: alpha-01
    volumes:
      - jempi-alpha-01-data:/dgraph
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_ALPHA_01_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_ALPHA_01_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph alpha --my=jempi-alpha-01:7080 --zero=jempi-zero-01:5080 --cache "size-mb=4096; percentage=50,30,20;" --security whitelist=0.0.0.0/0 --telemetry "sentry=false;"
    networks:
      jempi:

  jempi-ratel:
    image: ${JEMPI_RATEL_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_RATEL_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_RATEL_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    command: dgraph-ratel
    networks:
      jempi:

volumes:
  jempi-alpha-01-data:

networks:
  jempi:
    name: jempi_public
    external: true
