version: '3.9'

services:
  jempi-alpha-01:
    ports:
      - published: 8070
        target: 8080
        protocol: tcp
        mode: host
      - published: 9080
        target: 9080
        protocol: tcp
        mode: host

  jempi-ratel:
    ports:
      - published: 8010
        target: 8000
        protocol: tcp
        mode: host
