version: '3.9'

services:
  jempi-async-receiver:
    image: jembi/jempi-async-receiver:${JEMPI_ASYNC_RECEIVER_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_ASYNC_RECEIVER_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_ASYNC_RECEIVER_MEMORY_RESERVE}

  jempi-sync-receiver:
    image: jembi/jempi-sync-receiver:${JEMPI_SYNC_RECEIVER_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_SYNC_RECEIVER_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_SYNC_RECEIVER_MEMORY_RESERVE}

  jempi-pre-processor:
    image: jembi/jempi-pre-processor:${JEMPI_PRE_PROCESSOR_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_PRE_PROCESSOR_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_PRE_PROCESSOR_MEMORY_RESERVE}

  jempi-controller:
    image: jembi/jempi-controller:${JEMPI_CONTROLLER_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_CONTROLLER_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_CONTROLLER_MEMORY_RESERVE}

  jempi-em-calculator:
    image: jembi/jempi-em-calculator:${JEMPI_EM_CALCULATOR_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_EM_CALCULATOR_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_EM_CALCULATOR_MEMORY_RESERVE}

  jempi-linker:
    image: jembi/jempi-linker:${JEMPI_LINKER_IMAGE_TAG}
    environment:
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_LINKER_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_LINKER_MEMORY_RESERVE}

  jempi-postgresql:
    image: bitnami/postgresql:15.2.0
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${JEMPI_POSTGRES_CPU_LIMIT}
          memory: ${JEMPI_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${JEMPI_POSTGRES_CPU_RESERVE}
          memory: ${JEMPI_POSTGRES_MEMORY_RESERVE}
    volumes:
      - "jempi-psql-01-data:/bitnami/postgresql"
    configs:
      - target: /docker-entrypoint-initdb.d/jempi_psql_init_db.sql
        source: jempi_psql_init_db.sql

volumes:
  jempi-psql-01-data:


configs:
  jempi_psql_init_db.sql:
    file: ./importer/jempi_psql_init_db.sql
    name: jempi_psql_init_db.sql-${jempi_psql_init_db_sql_DIGEST:?err}
    labels:
      name: jempi
