version: '3.9'

services:
  jempi-zero-01:
    ports:
      - published: 5080
        target: 5080
        protocol: tcp
        mode: host
      - published: 6080
        target: 6080
        protocol: tcp
        mode: host
