version: '3.9'

services:
  jempi-kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    environment:
      KAFKA_BROKERCONNECT: 'jempi-kafka-01:9092,jempi-kafka-02:9092,jempi-kafka-03:9092'
      JVM_OPTS: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
      CMD_ARGS: '--server.port=9013 --management.server.port=9013'
    deploy:
      resources:
        limits:
          cpus: ${JEMPI_KAFDROP_CPU_LIMIT}
          memory: ${JEMPI_KAFDROP_MEMORY_LIMIT}
        reservations:
          cpus: ${JEMPI_KAFDROP_CPU_RESERVE}
          memory: ${JEMPI_KAFDROP_MEMORY_RESERVE}
