version: '3.9'

services:
  jempi-sync-receiver:
    ports:
      - published: 50040
        target: 50000
        protocol: tcp
        mode: host

  jempi-controller:
    ports:
      - published: 50020
        target: 50000
        protocol: tcp
        mode: host

  jempi-linker:
    ports:
      - published: 50010
        target: 50000
        protocol: tcp
        mode: host

  jempi-postgresql:
    ports:
      - published: 5432
        target: 5435
        mode: host
