version: '3.9'

services:
  # container for executing config import scripts for creating the OpenHIM channels used by the Mediator
  fhir-ig-importer-config-importer:
    image: node:erbium-alpine
    networks:
      openhim:
      default:
    environment:
      OPENHIM_API_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_API_PASSWORD: ${OPENHIM_PASSWORD}
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      OPENHIM_CONSOLE_BASE_URL: ${OPENHIM_CONSOLE_BASE_URL}
    command: sh -c "node openhimConfig.js"
    configs:
      - source: fhir-ig-importer-config-importer-openhimConfig.js
        target: /openhimConfig.js
      - source: fhir-ig-importer-config-importer-openhim-import.json
        target: /openhim-import.json
      - source: fhir-ig-importer-config-importer-ig-importer-app.json
        target: /ig-importer-app.json
    deploy:
      replicas: 1
      restart_policy:
        condition: none

configs:
  fhir-ig-importer-config-importer-openhimConfig.js:
    file: ./volume/openhimConfig.js
    name: fhir-ig-importer-config-importer-openhimConfig.js-${fhir_ig_importer_config_importer_openhimConfig_js_DIGEST:?err}
    labels:
      name: fhir-ig-importer
  fhir-ig-importer-config-importer-openhim-import.json:
    file: ./volume/openhim-import.json
    name: fhir-ig-importer-config-importer-openhim-import.json-${fhir_ig_importer_config_importer_openhim_import_js_DIGEST:?err}
    labels:
      name: fhir-ig-importer
  fhir-ig-importer-config-importer-ig-importer-app.json:
    file: ./volume/ig-importer-app.json
    name: fhir-ig-importer-config-importer-ig-importer-app.json-${fhir_ig_importer_config_importer_ig_importer_app_DIGEST:?err}
    labels:
      name: fhir-ig-importer

networks:
  openhim:
    name: openhim_public
    external: true
  default:
