version: '3.9'

services:
  elastic-search-config-importer:
    image: jembi/api-config-importer:1.1.0
    environment:
      HTTP_METHOD: 'PUT'
      SERVICE_NAME: '${ES_LEADER_NODE:-analytics-datastore-elastic-search}'
      SERVICE_API_PORT: 9200
      API_USERNAME: elastic
      API_PASSWORD: ${ES_ELASTIC:-dev_password_only}
      SSL: ${ES_SSL:-false}
      API_PATH: '/fhir-enrich-reports'
      MIME_TYPE: 'application/json'
      CONFIG_FILE: 'fhir-enrich-reports.json'
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    configs:
      - target: /fhir-enrich-reports.json
        source: fhir-enrich-reports.json

configs:
  fhir-enrich-reports.json:
    file: ./fhir-enrich-reports.json
    name: fhir-enrich-reports.json-${ferj_DIGEST:-csig_ferj_DIGEST}
    labels:
      name: elastic-search
