version: '3.9'

services:
  analytics-datastore-clickhouse-01:
    ports:
      - target: 8123
        published: 8123
        mode: host
      - target: 9000
        published: 9000
        mode: host

  analytics-datastore-clickhouse-02:
    ports:
      - target: 8123
        published: 8123
        mode: host
      - target: 9000
        published: 9000
        mode: host

  analytics-datastore-clickhouse-03:
    ports:
      - target: 8123
        published: 8123
        mode: host
      - target: 9000
        published: 9000
        mode: host

  clickhouse-keeper-01:
    ports:
      - target: 9181
        published: 9181
        mode: host

  clickhouse-keeper-02:
    ports:
      - target: 9181
        published: 9181
        mode: host

  clickhouse-keeper-03:
    ports:
      - target: 9181
        published: 9181
        mode: host
