version: '3.9'

services:
  analytics-datastore-clickhouse-01:
    image: clickhouse/clickhouse-server:latest
    user: "101:101"
    container_name: analytics-datastore-clickhouse-01
    hostname: analytics-datastore-clickhouse-01
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-1"
    volumes:
      - ${PWD}/configs/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/configs/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse-data-01:/var/lib/clickhouse/
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      public:
      default:

  analytics-datastore-clickhouse-02:
    image: clickhouse/clickhouse-server:latest
    user: "101:101"
    container_name: analytics-datastore-clickhouse-02
    hostname: analytics-datastore-clickhouse-02
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-2"
    volumes:
      - ${PWD}/configs/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/configs/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse-data-02:/var/lib/clickhouse/
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      public:
      default:

  analytics-datastore-clickhouse-03:
    image: clickhouse/clickhouse-server:latest
    user: "101:101"
    container_name: analytics-datastore-clickhouse-03
    hostname: analytics-datastore-clickhouse-03
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-3"
    volumes:
      - ${PWD}/configs/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/configs/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse-data-03:/var/lib/clickhouse/
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      public:
      default:

  clickhouse-keeper-01:
    image: clickhouse/clickhouse-keeper:latest-alpine
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-1"
    volumes:
     - ${PWD}/configs/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: clickhouse/clickhouse-keeper:latest-alpine
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-2"
    volumes:
     - ${PWD}/configs/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: clickhouse/clickhouse-keeper:latest-alpine
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-3"
    volumes:
     - ${PWD}/configs/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

volumes:
  clickhouse-data-01:
  clickhouse-data-02:
  clickhouse-data-03:

networks:
  public:
    name: clickhouse_public
    external: true
  default:
