version: "3.9"

services:
  analytics-datastore-clickhouse:
    image: ${CLICKHOUSE_IMAGE}
    ulimits:
      noFile: 262144
    environment:
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    configs:
      - target: /etc/clickhouse-server/config.d/metric_log.xml
        source: clickhouse_metric_log.xml
      - target: /etc/clickhouse-server/config.d/part_log.xml
        source: clickhouse_part_log.xml
      - target: /etc/clickhouse-server/config.d/query_log.xml
        source: clickhouse_query_log.xml
      - target: /etc/clickhouse-server/config.d/trace_log.xml
        source: clickhouse_trace_log.xml
    networks:
      public:
      reverse-proxy:
      default:

volumes:
  clickhouse-data:

configs:
  clickhouse_metric_log.xml:
    file: ./general_configs/metric_log.xml
    name: metric_log.xml.xml-${metric_log_xml_DIGEST:?err}
    labels:
      name: clickhouse
  clickhouse_part_log.xml:
    file: ./general_configs/part_log.xml
    name: part_log.xml.xml-${part_log_xml_DIGEST:?err}
    labels:
      name: clickhouse
  clickhouse_query_log.xml:
    file: ./general_configs/query_log.xml
    name: query_log.xml.xml-${query_log_xml_DIGEST:?err}
    labels:
      name: clickhouse
  clickhouse_trace_log.xml:
    file: ./general_configs/trace_log.xml
    name: trace_log.xml.xml-${trace_log_xml_DIGEST:?err}
    labels:
      name: clickhouse

networks:
  public:
    name: clickhouse_public
    external: true
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  default:
