version: '3.9'

services:
  zookeeper-1:
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-1-volume:/bitnami/zookeeper
    deploy:
      resources:
        limits:
          cpus: ${ZOOKEEPER_CPU_LIMIT}
          memory: ${ZOOKEEPER_MEMORY_LIMIT}
        reservations:
          cpus: ${ZOOKEEPER_CPU_RESERVE}
          memory: ${ZOOKEEPER_MEMORY_RESERVE}

volumes:
  zookeeper-1-volume:
