version: '3.9'

services:
  zookeeper-1:
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"
      resources:
        limits:
          cpus: ${ZOOKEEPER_CPU_LIMIT}
          memory: ${ZOOKEEPER_MEMORY_LIMIT}
        reservations:
          cpus: ${ZOOKEEPER_CPU_RESERVE}
          memory: ${ZOOKEEPER_MEMORY_RESERVE}

  zookeeper-2:
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-1:2888:3888,0.0.0.0:2888:3888,zookeeper-3:2888:3888
    volumes:
      - zookeeper-2-volume:/bitnami/zookeeper
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      resources:
        limits:
          cpus: ${ZOOKEEPER_CPU_LIMIT}
          memory: ${ZOOKEEPER_MEMORY_LIMIT}
        reservations:
          cpus: ${ZOOKEEPER_CPU_RESERVE}
          memory: ${ZOOKEEPER_MEMORY_RESERVE}

  zookeeper-3:
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,0.0.0.0:2888:3888
    volumes:
      - zookeeper-3-volume:/bitnami/zookeeper
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      resources:
        limits:
          cpus: ${ZOOKEEPER_CPU_LIMIT}
          memory: ${ZOOKEEPER_MEMORY_LIMIT}
        reservations:
          cpus: ${ZOOKEEPER_CPU_RESERVE}
          memory: ${ZOOKEEPER_MEMORY_RESERVE}

  kafka:
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: ${KAFKA_INSTANCES}
      resources:
        limits:
          cpus: ${KAFKA_CPU_LIMIT}
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          cpus: ${KAFKA_CPU_RESERVE}
          memory: ${KAFKA_MEMORY_RESERVE}

volumes:
  kafka-volume:
  zookeeper-2-volume:
  zookeeper-3-volume:
