version: '3.9'

services:
  kafka:
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: ${KAFKA_INSTANCES}
      resources:
        limits:
          cpus: ${KAFKA_CPU_LIMIT}
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          cpus: ${KAFKA_CPU_RESERVE}
          memory: ${KAFKA_MEMORY_RESERVE}

volumes:
  kafka-volume:
