version: "3.9"

services:
  kafka-unbundler-consumer:
    image: ${KAFKA_UNBUNDLER_CONSUMER_IMAGE}
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
    networks:
      kafka:

networks:
  kafka:
    name: kafka_public
    external: true
