version: "3.9"

services:
  santedb-mpi:
    image: ${SANTEMPI_IMAGE}
    networks:
      mpi:
      public:
      reverse-proxy:
      traefik:
      default:
      postgres:
    environment:
      - SDB_FEATURE=LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS;MDM;MATCHING;ADO_FTS
      - SDB_MATCHING_MODE=WEIGHTED
      - SDB_MDM_RESOURCE=Patient=org.santedb.matching.patient.default
      - SDB_MDM_AUTO_MERGE=false
      - SDB_DB_MAIN=server=${SANTEMPI_DB_REP_SET};port=5432; database=santedb; user id=${POSTGRESQL_USERNAME}; password=${POSTGRESQL_PASSWORD}; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      - SDB_DB_AUDIT=server=${SANTEMPI_DB_REP_SET};port=5432; database=auditdb; user id=${POSTGRESQL_USERNAME}; password=${POSTGRESQL_PASSWORD}; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      - SDB_DB_MAIN_PROVIDER=Npgsql
      - SDB_DB_AUDIT_PROVIDER=Npgsql
      - SDB_DATA_POLICY_ACTION=HIDE
      - SDB_DATA_POLICY_RESOURCE=Patient
      - SDB_DELAY_START=5000
    deploy:
      replicas: ${SANTEMPI_INSTANCES}
      labels:
        - traefik.enable=true
        - traefik.docker.network=reverse-proxy-traefik_public
        - traefik.http.routers.santedb-mpi.service=santedb-mpi
        - traefik.http.services.santedb-mpi.loadbalancer.server.port=8080
        - traefik.http.routers.santedb-mpi.rule=Host(`${SANTEDB_MPI_TRAEFIK_SUBDOMAIN}.${DOMAIN_NAME_HOST_TRAEFIK}`)
    volumes:
      - santedb-data:/santedb

  santedb-www:
    image: ${SANTEDB_WWW_IMAGE}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=reverse-proxy-traefik_public
        - traefik.http.routers.santedb-www.service=santedb-www
        - traefik.http.services.santedb-www.loadbalancer.server.port=9200
        - traefik.http.routers.santedb-www.rule=Host(`${SANTEDB_WWW_TRAEFIK_SUBDOMAIN}.${DOMAIN_NAME_HOST_TRAEFIK}`)
    networks:
      default:
      reverse-proxy:
      traefik:

# Sante's Match configuration is stored in the container. This will prevent the matching rules of the client registry from being lost. A docker config cannot be used for this case as the settings can be changed on Sante's UI.
volumes:
  santedb-data:

networks:
  mpi:
    name: mpi_public
    external: true
  public:
    name: santedb_public
    external: true
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  traefik:
    name: reverse-proxy-traefik_public
    external: true
  default:
  postgres:
    name: postgres_public
    external: true
