version: '3.9'

services:
  santedb-mpi:
    image: santesuite/santedb-mpi:2.2.3
    environment:
      - SDB_FEATURE=LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS;MDM;MATCHING;ADO_FTS
      - SDB_MATCHING_MODE=WEIGHTED
      - SDB_MDM_RESOURCE=Patient=org.santedb.matching.patient.default
      - SDB_MDM_AUTO_MERGE=false
      - SDB_DB_MAIN=${SANTEMPI_MAIN_CONNECTION_STRING:-server=santempi-psql-1;port=5432; database=santedb; user id=santedb; password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;}
      - SDB_DB_AUDIT=${SANTEMPI_AUDIT_CONNECTION_STRING:-server=santempi-psql-1;port=5432; database=auditdb; user id=santedb; password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;}
      - SDB_DB_MAIN_PROVIDER=Npgsql
      - SDB_DB_AUDIT_PROVIDER=Npgsql
      - SDB_DATA_POLICY_ACTION=HIDE
      - SDB_DATA_POLICY_RESOURCE=Patient
      - SDB_DELAY_START=5000
    deploy:
      replicas: ${SANTEMPI_INSTANCES}
      resources:
        limits:
          cpus: ${SANTE_MPI_CPU_LIMIT:-0}
          memory: ${SANTE_MPI_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${SANTE_MPI_CPU_RESERVE:-0.05}
          memory: ${SANTE_MPI_MEMORY_RESERVE:-500M}
    volumes:
         - santedb-data:/santedb
         
  santedb-www:
    image: santesuite/santedb-www:2.2.1.10
    deploy:
      resources:
        limits:
          cpus: ${SANTE_WWW_CPU_LIMIT:-0}
          memory: ${SANTE_WWW_MEMORY_LIMIT:-2G}
        reservations:
          cpus: ${SANTE_WWW_CPU_RESERVE:-0.05}
          memory: ${SANTE_WWW_MEMORY_RESERVE:-500M}
    depends_on:
      - santedb-mpi

# Sante's Match configuration is stored in the container. This will prevent the matching rules of the client registry from being lost. A docker config cannot be used for this case as the settings can be changed on Sante's UI.
volumes: 
  santedb-data:
