version: '3.9'

services:
  santedb-mpi:
    ports:
      - target: 8080
        published: 8084
        mode: host
      - target: 2100
        published: 2100
        mode: host
  santedb-www:
    ports:
      - target: 9200
        published: 9200
        mode: host
