version: '3.9'

services:
  santempi-psql-1:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  santempi-psql-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${SANTEMPI_POSTGRESQL_PASSWORD:-SanteDB123}
      POSTGRESQL_USERNAME: ${SANTEMPI_POSTGRESQL_USERNAME:-santempi}
      REPMGR_NODE_NETWORK_NAME: santempi-psql-2
      REPMGR_PASSWORD: SanteDB123
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: santempi-psql-2
      REPMGR_PRIMARY_HOST: ${SANTEMPI_REPMGR_PRIMARY_HOST:-santempi-psql-1}
      REPMGR_PARTNER_NODES: ${SANTEMPI_REPMGR_PARTNER_NODES:-santempi-psql-1,santempi-psql-2,santempi-psql-3}
    volumes:
      - 'santempi-psql-2-data:/bitnami/postgresql'
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.name==node-2"

  santempi-psql-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${SANTEMPI_POSTGRESQL_PASSWORD:-SanteDB123}
      POSTGRESQL_USERNAME: ${SANTEMPI_POSTGRESQL_USERNAME:-santempi}
      REPMGR_NODE_NETWORK_NAME: santempi-psql-3
      REPMGR_PASSWORD: SanteDB123
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: santempi-psql-3
      REPMGR_PRIMARY_HOST: ${SANTEMPI_REPMGR_PRIMARY_HOST:-santempi-psql-1}
      REPMGR_PARTNER_NODES: ${SANTEMPI_REPMGR_PARTNER_NODES:-santempi-psql-1,santempi-psql-2,santempi-psql-3}
    volumes:
      - 'santempi-psql-3-data:/bitnami/postgresql'
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.name==node-3"

volumes:
  santempi-psql-2-data:
  santempi-psql-3-data:
