name: Create go binaries for linux, windows and mac

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # replaces latest with the version of the release in the config.yaml file
      - name: Set version
        run: |
          sed -i "s/latest/${{ github.event.release.tag_name }}/g" config.yaml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./config.yaml
            ./cdr-dw.env
            ./cdr.env
            ./mpi.env
